mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
            path('polls/', include("polls.urls")),
            path('admin/', admin.site.urls),
            

]

polls/urls.py
from django.urls import path

from . import views
app_name="polls"
urlpatterns = [
    path("", views.index, name="index"),

    path("<int:question_id>/", views.detail, name="detail"),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),    
    path("<int:question_id>/choice/", views.choice, name="choice"),
    path("<int:question_id>/newchoice/", views.newchoice, name="newchoice"),
    path("<int:question_id>/reset/", views.resetVote, name="reset"), 
    path("new/", views.newQs, name="new"),    
   
    
   

]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

class Question(models.Model):
     

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from .models import Choice, Question
from django.template import loader
from django.http import Http404
from django.urls import reverse
from django.shortcuts import get_object_or_404,render
from django.utils import timezone
def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {"latest_question_list": latest_question_list}
    return render(request, "polls/index.html", context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/detail.html", {"question": question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))


def choice(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/choice.html", {"question": question})


def newchoice(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        new_choice=request.POST["choice"]
        if not new_choice:
            raise KeyError
            
    except (KeyError):
        return render(
            request,
            "polls/detail.html",
            {
                "question":question,
                "error_message":"choice cannot be added"
            }
        )
    else:
        n_choice= Choice(
            question=question,
            choice_text=new_choice,
        )
        n_choice.save()
        return HttpResponseRedirect(reverse("polls:detail", args=(question.id,)))
    
def resetVote(request, question_id):
        question = get_object_or_404(Question, pk=question_id)
        for choice in question.choice_set.all():
            choice.votes=0
            choice.save()
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))
def newQs(request):
    if request.method == 'GET':
        return render(request, "polls/newQs.html", {})
    elif request.method == 'POST':
        user_submitted_question = request.POST["question"]
        if not user_submitted_question:
            return render(request, "polls/newQs.html", {
                "error_message":"please enter a valid qs"
            })

        new_question = Question(
            question_text=user_submitted_question,
            pub_date=timezone.now(),
        )
        new_question.save()
    return HttpResponseRedirect(reverse("polls:index",))

polls/templates/polls/choice.html
<form action="{% url 'polls:newchoice' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>Add new choice for "{{ question.question_text }}"</h1></legend>
         <label>Add choice</label>
         <input type="text" name="choice">
    </fieldset>
    <input type="submit" value="Add choice">
    </form>

polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
        <a href="{% url 'polls:choice' question.id %}">Add choice?</a>
    </fieldset>
    <input type="submit" value="Vote">
    </form>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<a href="{% url 'polls:new'  %}">Add Question?</a>

polls/templates/polls/newQs.html
<form action="{% url 'polls:new' %}" method="post">
    {% csrf_token %}
    <h1>Lets Add New Question</h1>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <label for="choice">Enter your question:</label>
    <input type="text" value="" name="question">
    <input type="submit" value="add" id="question">

</form>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
<a href="{% url 'polls:reset' question.id %}">Reset Vote?</a>